version: 2

jobs:
  deploy:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "sudo systemctl restart snuboard-server"

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main 
